package de.htwsaar.sose2024.ase.fourpeopleteam;

import java.util.Scanner;

/**
 * The class CommandLineInterface implements the class UserInterface. It provides an implementation for the classes
 * getInput() and show() declared in UserInterface
 */
public class CommandLineInterface implements UserInterface {
  private Scanner scanner;


  /**
   * Displays the specified content to the command line
   *
   * @param content the content generated by the AI
   */
  @Override
  public void show(String content) {
    System.out.println(content);
  }


  /**
   * This method gets the user input. It prompts the user for input and reads it from the command line
   */
  @Override
  public String getInput() {
    System.out.println("Ask me something\n");
    System.out.print("> ");
    return scanner.nextLine();
  }


  /**
   * Construct a CommandLineInterface and initializes the scanner to read input from the command line
   */
  public CommandLineInterface() {
    scanner = new Scanner(System.in, "UTF_8");
  }
}